
import {useState, useEffect } from 'react';
import {v4 as uuidv4} from 'uuid';

const CERTIFICATIONS_DATA = [
  {
    id: uuidv4(),
    course:"Static Web Development (HTML & CSS)",
    issuer: 'NXTWave CCBP4.O',
    date: '2022',
    certificateURL: '/certificates/STATIC_WEB_HTML_CSS.png'
  },
    {
    id: uuidv4(),
    course:"Responsive Web Development (HTML & CSS-Flexbox & Grid)",
    issuer: 'NXTWave CCBP4.O',
    date: '2023',
    certificateURL: '/certificates/RESPONSIVE_WEB_HTML_CSS.png'
  },
  {
    id: uuidv4(),
    course:"Dynamic Web Development (JavaScript)",
    issuer: 'NXTWave CCBP4.O',
    date: '2023',
    certificateURL: '/certificates/DYNAMIC_WEB_JAVASCRIPT.png'
  },
    {
    id: uuidv4(),
    course:"JavaScript Essentials",
    issuer: 'NXTWave CCBP4.O',
    date: '2023',
    certificateURL: '/certificates/JAVASCRIPT_ESSENTIALS.png'
  },
  {
    id: uuidv4(),
    course:"Programming Foundations with Python",
    issuer: 'NXTWave CCBP4.O',
    date: '2023',
    certificateURL: '/certificates/PROGRAMMING_FOUNDATIONS_PYTHON.png'
  }, 

  {
    id: uuidv4(),
    course:"SQL Database (SQLite)",
    issuer: 'NXTWave CCBP4.O',
    date: '2024',
    certificateURL: '/certificates/SQL_DATABASE.png'
  },

  
  {
    id: uuidv4(),
    course:"ReactJS Development",
    issuer: 'NXTWave CCBP4.O',
    date: '2024',
    certificateURL: '/certificates/REACTJS.png'
  },

  {
    id: uuidv4(),
    course:"Developer Foundations (Git & GitHub)",
    issuer: 'NXTWave CCBP4.O',
    date: '2025',
    certificateURL: '/certificates/DEVELOPER_FOUNDATIONS_GIT.png'
  },
  {
    id: uuidv4(),
    course:"NodeJS Development",
    issuer: 'NXTWave CCBP4.O',
    date: '2025',
    certificateURL: '/certificates/NODEJS.png'
  },
  {
    id: uuidv4(),
    course:"Internship Certification",
    issuer: 'Unified Mentor, Frontend Development',
    date: '2025',
    certificateURL: '/certificates/INTERNSHIP_CERTIFICATION.png'
  },
  {
    id: uuidv4(),
    course:"MongoDB Certification (Self Learning)",
    issuer: 'AI Assisted - (Generated by ChatGPT)',
    date: '2026',
    certificateURL: '/certificates/MONGODB_CERTIFICATION_SELF_LEARNING.png'
  },



]

const Certifications = () => {
  const [showAnimation, setShowAnimation] = useState(false); 

  useEffect(() => {
    setShowAnimation(true)
  }, [])

  return (
    <div  className="min-h-screen bg-gray-50 dark:bg-gray-950 flex flex-col justify-start items-center pt-20 md:pt-24 pb-5">
   <h1 className="text-2xl md:text-4xl text-gray-950 dark:text-gray-50 font-poppins font-bold inline-block border-b-4 border-blue-600 pb-1 md:pb-2">Certifications</h1>
    {/* Content section */}
    <div className="w-11/12 md:w-4/5 flex flex-col justify-center items-center mt-6 md:mt-10">
      <ul className="w-full grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {CERTIFICATIONS_DATA.map((eachItem, index) => (
          <li key={eachItem.id} 
            className={`flex flex-col mb-6 p-5 rounded-lg shadow-md bg-gray-100 dark:bg-gray-800
                transform transition-all duration-700 ease-out
                ${showAnimation 
                  ? "opacity-100 translate-y-0" 
                  : "opacity-0 translate-y-8"}`}
                style={{ transitionDelay: `${index * 100}ms` }}
              >

           
            
            <section className="h-100 w-120 bg-white dark:bg-black shadow-sm rounded-lg p-3 mb-2">
            <img src={eachItem.certificateURL} alt={`${eachItem.course} Certificate`} className="w-fit rounded-lg shadow-md overflow-hidden" />
            </section>

            <h1 className="text-gray-900 dark:text-gray-100 font-roboto font-bold text-xl">{eachItem.course}</h1>
            <p className="text-blue-600 dark:text-blue-400 font-roboto mt-1 text-sm md:text-base">{eachItem.issuer} - {eachItem.date}</p>
            <a href={eachItem.certificateURL} target="_blank" rel="noopener noreferrer" className="text-blue-500 dark:text-blue-300 mt-2 text-[10px] md:text-xs underline">Detailed View Certificate</a>
          </li>
        ))}
      </ul>
    </div>



    </div> 
     ) 
  } 


  export default Certifications